apiVersion: v1
kind: Service
metadata:
  name: music-app-service
  namespace: music-app-namespace
spec:
  selector:
    app: music-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501  # Make sure this matches the port your Streamlit app is running on
