name: Deploy Image docker hub

on:
  push:
    branches:
      - dev
jobs:
  push-image-to-docker-hub:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4 # first action : checkout source code
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:  
          file: main/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/clockbox:latest


  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Configure AWS credentials for dev branch
        if: github.ref == 'refs/heads/dev'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-west-2  # Change to your desired region
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
      # - name: Terraform Plan
      #   run: |
      #     cd terraform
      #     terraform plan -out=tfplan
  
      # - name: Terraform Apply
      #   run: |
      #     cd terraform
      #     terraform apply -auto-approve tfplan



  