name: Deploy Image docker hub

on:
  push:
    branches:
      - dev
jobs:
  push-image-to-docker-hub:  # job name
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      REPO_NAME: ${{secrets.REPO_NAME}}
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2 # first action : checkout source code
    
    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: main/Dockerfile

    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
    - name: Docker Push
      run: docker push thang14112005/music-app:${{ steps.date.outputs.date }}


  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Configure AWS credentials for dev branch
        if: github.ref == 'refs/heads/dev'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-west-2  # Change to your desired region
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
      # - name: Terraform Plan
      #   run: |
      #     cd terraform
      #     terraform plan -out=tfplan
  
      # - name: Terraform Apply
      #   run: |
      #     cd terraform
      #     terraform apply -auto-approve tfplan



  