name: CD production

on:
  push:
    branches:
      - main
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-west-2  # Change to your desired region
      
      # - name: Configure AWS credentials for dev branch
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      #     aws-region: us-west-2  # Change to your desired region
      
      # - name: Configure AWS credentials for staging branch
      #   if: github.ref == 'refs/heads/staging'  # Add this condition for staging branch
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      #     aws-region: us-west-2  # Change to your desired region
      
      # - name: Zip Lambda files
      #   run: |
      #       mkdir -p terraform/lambda/lambda
      #       zip -r terraform/lambda/lambda/lambda_zip.zip lambda_function.py module_post.py module_delete_link.py bin pytube pytube-15.0.0.dist-info
      #   working-directory: terraform    

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve tfplan

      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build and push
        uses: docker/build-push-action@v5
        with:  
            context: ./main
            file: ./main/Dockerfile
            push: true
            tags: thang14112005/music-app:latest
  